import type { Metadata } from "next";
import { Inter , Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import Header from "./new components/Header";
import Footer from "./new components/Footer";
import MobileNavbar from "./components/MobileNavbar";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400','500','700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans .className}>
      {/* <Navbar/> */}
      <Header />
      <MobileNavbar />
        {children} 
      {/* <Footer /> */}
      <Footer />
      </body>
    </html>
  );
}
